export const CATEGORIES = [
  "Bánh sinh nhật",
  "Bánh kem",
  "Cupcake",
  "Bánh mì & Croissant",
  "Donut",
  "Bánh quy",
  "Bánh Trung thu",
  "Bánh su kem",
];

export const PRODUCTS = [
  {
    id: "bsn-1",
    name: "Bánh sinh nhật Chocolate Fudge",
    category: "Bánh sinh nhật",
    price: 320000,
    emoji: "🎂",
    desc: "Cốt bánh chocolate ẩm mềm, phủ kem fudge đậm vị, trang trí theo yêu cầu.",
    images: ["/products/bsn-1.jpg"],
  },
  {
    id: "bsn-2",
    name: "Bánh sinh nhật Vani Dâu",
    category: "Bánh sinh nhật",
    price: 280000,
    emoji: "🎂",
    desc: "Cốt vani mềm xốp, xen lớp dâu tươi và kem tươi thanh nhẹ, hợp tiệc nhỏ.",
  },
  {
    id: "bsn-3",
    name: "Bánh sinh nhật Matcha Đậu Đỏ",
    category: "Bánh sinh nhật",
    price: 340000,
    emoji: "🎂",
    desc: "Vị matcha thanh, không quá ngọt, hoà cùng đậu đỏ bùi béo.",
  },
  {
    id: "bk-1",
    name: "Bánh kem Dâu Tây Classic",
    category: "Bánh kem",
    price: 260000,
    emoji: "🍰",
    desc: "Kem tươi mịn, phủ dâu tây tươi, ngọt thanh dịu nhẹ.",
  },
  {
    id: "bk-2",
    name: "Bánh kem Xoài Nhiệt Đới",
    category: "Bánh kem",
    price: 250000,
    emoji: "🍰",
    desc: "Kem xoài tươi mát, cốt bánh bông lan mềm, thích hợp mùa hè.",
  },
  {
    id: "bk-3",
    name: "Bánh kem Chocolate Đắng",
    category: "Bánh kem",
    price: 270000,
    emoji: "🍰",
    desc: "Vị chocolate đắng nhẹ dành cho người không thích quá ngọt.",
  },
  {
    id: "cc-1",
    name: "Cupcake Red Velvet",
    category: "Cupcake",
    price: 35000,
    emoji: "🧁",
    desc: "Cốt bánh đỏ mềm mịn, phủ kem phô mai béo nhẹ, xinh xắn cho tiệc nhỏ.",
  },
  {
    id: "cc-2",
    name: "Cupcake Vani Rắc Kẹo",
    category: "Cupcake",
    price: 30000,
    emoji: "🧁",
    desc: "Vị vani ngọt dịu, trang trí kẹo màu sắc, hợp sinh nhật trẻ em.",
  },
  {
    id: "cc-3",
    name: "Cupcake Chocolate Nutella",
    category: "Cupcake",
    price: 38000,
    emoji: "🧁",
    desc: "Nhân Nutella béo ngậy, phủ kem chocolate đậm đà.",
  },
  {
    id: "bm-1",
    name: "Croissant Bơ Pháp",
    category: "Bánh mì & Croissant",
    price: 32000,
    emoji: "🥐",
    desc: "Vỏ giòn tan nhiều lớp, thơm bơ, ủ men tự nhiên mỗi sáng.",
  },
  {
    id: "bm-2",
    name: "Bánh mì Sourdough",
    category: "Bánh mì & Croissant",
    price: 45000,
    emoji: "🥐",
    desc: "Vỏ giòn, ruột dai nhẹ, vị chua thanh tự nhiên.",
  },
  {
    id: "bm-3",
    name: "Croissant Nhân Hạnh Nhân",
    category: "Bánh mì & Croissant",
    price: 38000,
    emoji: "🥐",
    desc: "Nhân kem hạnh nhân béo bùi, phủ hạnh nhân lát rang thơm.",
  },
  {
    id: "dn-1",
    name: "Donut Glazed Truyền Thống",
    category: "Donut",
    price: 22000,
    emoji: "🍩",
    desc: "Mềm xốp, phủ lớp đường glazed mỏng, ngọt vừa phải.",
  },
  {
    id: "dn-2",
    name: "Donut Chocolate Topping",
    category: "Donut",
    price: 25000,
    emoji: "🍩",
    desc: "Phủ chocolate đậm vị, rắc topping giòn tan.",
  },
  {
    id: "dn-3",
    name: "Donut Matcha Trà Xanh",
    category: "Donut",
    price: 26000,
    emoji: "🍩",
    desc: "Vị matcha thanh nhẹ, không quá ngọt, màu sắc bắt mắt.",
  },
  {
    id: "bq-1",
    name: "Bánh quy Bơ Đan Mạch",
    category: "Bánh quy",
    price: 85000,
    emoji: "🍪",
    desc: "Giòn rụm, thơm bơ đậm đà, đóng hộp thiếc làm quà tặng.",
  },
  {
    id: "bq-2",
    name: "Bánh quy Chocolate Chip",
    category: "Bánh quy",
    price: 75000,
    emoji: "🍪",
    desc: "Giòn ngoài mềm trong, nhiều chocolate chip béo ngậy.",
  },
  {
    id: "bq-3",
    name: "Bánh quy Oreo",
    category: "Bánh quy",
    price: 48500,
    emoji: "🍪",
    desc: "Vỏ bánh quy bơ giòn tan hoà cùng vụn Oreo đen béo bùi, vị chocolate đậm đà khó cưỡng.",
  },
  {
    id: "tt-1",
    name: "Bánh Trung thu Đậu Xanh Trứng Muối",
    category: "Bánh Trung thu",
    price: 95000,
    emoji: "🥮",
    desc: "Nhân đậu xanh bùi béo, trứng muối mặn ngọt hài hoà, vị truyền thống.",
  },
  {
    id: "tt-2",
    name: "Bánh Trung thu Trà Xanh Hạt Sen",
    category: "Bánh Trung thu",
    price: 98000,
    emoji: "🥮",
    desc: "Nhân hạt sen thanh mát kết hợp trà xanh, không quá ngọt.",
  },
  {
    id: "tt-3",
    name: "Bánh Trung thu thập cẩm",
    category: "Bánh Trung thu",
    price: 130000,
    emoji: "🥮",
    desc: "Nhân thập cẩm nhiều loại hạt, mứt bí, lạp xưởng hoà quyện, đậm đà hương vị Trung thu cổ truyền.",
  },
  {
    id: "sk-1",
    name: "Bánh su kem Nhân Kem Trứng",
    category: "Bánh su kem",
    price: 28000,
    emoji: "🍮",
    desc: "Vỏ bánh nhẹ tan, nhân kem trứng béo ngậy, thơm vani.",
  },
  {
    id: "sk-2",
    name: "Bánh su kem Nhân Chocolate",
    category: "Bánh su kem",
    price: 30000,
    emoji: "🍮",
    desc: "Nhân kem chocolate đậm vị, vỏ bánh giòn nhẹ.",
  },
  {
    id: "sk-3",
    name: "Bánh su kem nhân Phô mai",
    category: "Bánh su kem",
    price: 40000,
    emoji: "🍮",
    desc: "Vỏ bánh su nhẹ xốp, nhân phô mai kem béo mịn, vị mặn ngọt hài hoà tan ngay đầu lưỡi.",
  },
];
